// SPDX-FileCopyrightText: 2025 Nexa Contributors <contact@nexa.ms>
// SPDX-License-Identifier: AGPL-3.0-or-later

using NexaMediaServer.Core.DTOs;
using NexaMediaServer.Core.Entities;
using NexaMediaServer.Core.Enums;

namespace NexaMediaServer.Core.Services;

/// <summary>
/// Provides image persistence, caching, and artwork management for metadata items.
/// </summary>
public interface IImageService
{
    /// <summary>
    /// Gets a (cached or newly generated) transcoded image for the given request.
    /// </summary>
    /// <param name="request">Transcode parameters.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Absolute file path to cached transcoded image.</returns>
    Task<string> GetOrTranscodeAsync(
        ImageTranscodeRequest request,
        CancellationToken cancellationToken
    );

    /// <summary>
    /// Saves raw artwork bytes for a metadata item under its artwork subfolder and returns its URI.
    /// </summary>
    /// <param name="item">The metadata item.</param>
    /// <param name="agentIdentifier">Unique normalized metadata agent identifier.</param>
    /// <param name="kind">Artwork kind (poster, backdrop, logo).</param>
    /// <param name="imageBytes">Binary image data.</param>
    /// <param name="extension">Preferred file extension (e.g. jpg, png, webp). Defaults to jpg if null.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Canonical artwork URI (metadata://posters/{agent}_{uuid}).</returns>
    Task<string> SaveAgentArtworkAsync(
        MetadataItem item,
        string agentIdentifier,
        ArtworkKind kind,
        byte[] imageBytes,
        string? extension,
        CancellationToken cancellationToken
    );

    /// <summary>
    /// Saves thumbnail bytes generated by an image provider.
    /// </summary>
    /// <param name="metadataUuid">The metadata item identifier.</param>
    /// <param name="providerName">The image provider name.</param>
    /// <param name="imageBytes">Binary image data.</param>
    /// <param name="extension">Preferred file extension.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Thumbnail URI (metadata://thumbnails/{provider}_{uuid}).</returns>
    Task<string> SaveThumbnailAsync(
        Guid metadataUuid,
        string providerName,
        byte[] imageBytes,
        string? extension,
        CancellationToken cancellationToken
    );

    /// <summary>
    /// Chooses and sets the primary artwork for the specified kind using precedence rules:
    /// 1. Agent images in library-defined priority order.
    /// 2. Fallback to thumbnail if no agent image available.
    /// </summary>
    /// <param name="item">The metadata item.</param>
    /// <param name="kind">Artwork kind.</param>
    /// <param name="orderedAgentIdentifiers">Agent identifiers in precedence order.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Selected artwork URI or null if none found.</returns>
    Task<string?> SetPrimaryArtworkAsync(
        MetadataItem item,
        ArtworkKind kind,
        IReadOnlyList<string> orderedAgentIdentifiers,
        CancellationToken cancellationToken
    );
}
