// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: field_values.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getFieldValuesForItem = `-- name: GetFieldValuesForItem :many
SELECT id, object_id, field_id, position,
       text_value, integer_value, real_value, boolean_value, date_value, datetime_value, json_value
FROM field_values
WHERE object_id = ?
ORDER BY position, field_id
`

func (q *Queries) GetFieldValuesForItem(ctx context.Context, objectID string) ([]FieldValue, error) {
	rows, err := q.db.QueryContext(ctx, getFieldValuesForItem, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FieldValue
	for rows.Next() {
		var i FieldValue
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.FieldID,
			&i.Position,
			&i.TextValue,
			&i.IntegerValue,
			&i.RealValue,
			&i.BooleanValue,
			&i.DateValue,
			&i.DatetimeValue,
			&i.JsonValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFieldValue = `-- name: UpsertFieldValue :exec
INSERT INTO field_values (
    object_id, field_id, position,
    text_value, integer_value, real_value, boolean_value, date_value, datetime_value, json_value
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(object_id, field_id) DO UPDATE SET
    position = excluded.position,
    text_value = excluded.text_value,
    integer_value = excluded.integer_value,
    real_value = excluded.real_value,
    boolean_value = excluded.boolean_value,
    date_value = excluded.date_value,
    datetime_value = excluded.datetime_value,
    json_value = excluded.json_value
`

type UpsertFieldValueParams struct {
	ObjectID      string          `json:"object_id"`
	FieldID       string          `json:"field_id"`
	Position      int64           `json:"position"`
	TextValue     sql.NullString  `json:"text_value"`
	IntegerValue  sql.NullInt64   `json:"integer_value"`
	RealValue     sql.NullFloat64 `json:"real_value"`
	BooleanValue  sql.NullInt64   `json:"boolean_value"`
	DateValue     sql.NullString  `json:"date_value"`
	DatetimeValue sql.NullString  `json:"datetime_value"`
	JsonValue     sql.NullString  `json:"json_value"`
}

func (q *Queries) UpsertFieldValue(ctx context.Context, arg UpsertFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertFieldValue,
		arg.ObjectID,
		arg.FieldID,
		arg.Position,
		arg.TextValue,
		arg.IntegerValue,
		arg.RealValue,
		arg.BooleanValue,
		arg.DateValue,
		arg.DatetimeValue,
		arg.JsonValue,
	)
	return err
}
