// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: field_definitions.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createFieldDefinition = `-- name: CreateFieldDefinition :exec
INSERT INTO field_definitions (
    id, library_id, namespace, key, display_name, field_type,
    required, position, configuration_json, validation_json, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateFieldDefinitionParams struct {
	ID                string         `json:"id"`
	LibraryID         string         `json:"library_id"`
	Namespace         string         `json:"namespace"`
	Key               string         `json:"key"`
	DisplayName       string         `json:"display_name"`
	FieldType         string         `json:"field_type"`
	Required          int64          `json:"required"`
	Position          int64          `json:"position"`
	ConfigurationJson sql.NullString `json:"configuration_json"`
	ValidationJson    sql.NullString `json:"validation_json"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) CreateFieldDefinition(ctx context.Context, arg CreateFieldDefinitionParams) error {
	_, err := q.db.ExecContext(ctx, createFieldDefinition,
		arg.ID,
		arg.LibraryID,
		arg.Namespace,
		arg.Key,
		arg.DisplayName,
		arg.FieldType,
		arg.Required,
		arg.Position,
		arg.ConfigurationJson,
		arg.ValidationJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listFieldDefinitionsForLibrary = `-- name: ListFieldDefinitionsForLibrary :many
SELECT id, library_id, namespace, key, display_name, field_type,
       required, position, configuration_json, validation_json, created_at, updated_at
FROM field_definitions
WHERE library_id = ?
ORDER BY position, id
LIMIT ?
`

type ListFieldDefinitionsForLibraryParams struct {
	LibraryID string `json:"library_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListFieldDefinitionsForLibrary(ctx context.Context, arg ListFieldDefinitionsForLibraryParams) ([]FieldDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listFieldDefinitionsForLibrary, arg.LibraryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FieldDefinition
	for rows.Next() {
		var i FieldDefinition
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Namespace,
			&i.Key,
			&i.DisplayName,
			&i.FieldType,
			&i.Required,
			&i.Position,
			&i.ConfigurationJson,
			&i.ValidationJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
