// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_state.sql

package sqlcgen

import (
	"context"
)

const getInstanceState = `-- name: GetInstanceState :one
SELECT setup_state FROM instance_state WHERE id = 1
`

func (q *Queries) GetInstanceState(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getInstanceState)
	var setup_state string
	err := row.Scan(&setup_state)
	return setup_state, err
}

const upsertInstanceState = `-- name: UpsertInstanceState :exec
INSERT INTO instance_state (id, setup_state) VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET setup_state = excluded.setup_state, updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) UpsertInstanceState(ctx context.Context, setupState string) error {
	_, err := q.db.ExecContext(ctx, upsertInstanceState, setupState)
	return err
}
