// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"
)

const createItem = `-- name: CreateItem :exec
INSERT INTO items (id, library_id, status, revision, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateItemParams struct {
	ID        string `json:"id"`
	LibraryID string `json:"library_id"`
	Status    string `json:"status"`
	Revision  int64  `json:"revision"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.LibraryID,
		arg.Status,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, library_id, status, revision, created_at, updated_at
FROM items
WHERE id = ?
`

func (q *Queries) GetItem(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemsForLibraryAfterCursor = `-- name: ListItemsForLibraryAfterCursor :many
SELECT id, library_id, status, revision, created_at, updated_at
FROM items
WHERE library_id = ?
  AND (created_at > ? OR (created_at = ? AND id > ?))
ORDER BY created_at, id
LIMIT ?
`

type ListItemsForLibraryAfterCursorParams struct {
	LibraryID   string `json:"library_id"`
	CreatedAt   string `json:"created_at"`
	CreatedAt_2 string `json:"created_at_2"`
	ID          string `json:"id"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) ListItemsForLibraryAfterCursor(ctx context.Context, arg ListItemsForLibraryAfterCursorParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItemsForLibraryAfterCursor,
		arg.LibraryID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Status,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsForLibraryFirstPage = `-- name: ListItemsForLibraryFirstPage :many
SELECT id, library_id, status, revision, created_at, updated_at
FROM items
WHERE library_id = ?
ORDER BY created_at, id
LIMIT ?
`

type ListItemsForLibraryFirstPageParams struct {
	LibraryID string `json:"library_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListItemsForLibraryFirstPage(ctx context.Context, arg ListItemsForLibraryFirstPageParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItemsForLibraryFirstPage, arg.LibraryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Status,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
