// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: libraries.sql

package sqlcgen

import (
	"context"
)

const createLibrary = `-- name: CreateLibrary :exec
INSERT INTO libraries (id, slug, name, content_type, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateLibraryParams struct {
	ID          string `json:"id"`
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	ContentType string `json:"content_type"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) error {
	_, err := q.db.ExecContext(ctx, createLibrary,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.ContentType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getLibrary = `-- name: GetLibrary :one
SELECT id, slug, name, content_type, created_at, updated_at
FROM libraries
WHERE id = ?
`

func (q *Queries) GetLibrary(ctx context.Context, id string) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, slug, name, content_type, created_at, updated_at
FROM libraries
ORDER BY name, id
LIMIT ? OFFSET ?
`

type ListLibrariesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListLibraries(ctx context.Context, arg ListLibrariesParams) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listLibraries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ContentType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
