// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"database/sql"
)

type FieldDefinition struct {
	ID                string         `json:"id"`
	LibraryID         string         `json:"library_id"`
	Namespace         string         `json:"namespace"`
	Key               string         `json:"key"`
	DisplayName       string         `json:"display_name"`
	FieldType         string         `json:"field_type"`
	Required          int64          `json:"required"`
	Position          int64          `json:"position"`
	ConfigurationJson sql.NullString `json:"configuration_json"`
	ValidationJson    sql.NullString `json:"validation_json"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type FieldValue struct {
	ID            int64           `json:"id"`
	ObjectID      string          `json:"object_id"`
	FieldID       string          `json:"field_id"`
	Position      int64           `json:"position"`
	TextValue     sql.NullString  `json:"text_value"`
	IntegerValue  sql.NullInt64   `json:"integer_value"`
	RealValue     sql.NullFloat64 `json:"real_value"`
	BooleanValue  sql.NullInt64   `json:"boolean_value"`
	DateValue     sql.NullString  `json:"date_value"`
	DatetimeValue sql.NullString  `json:"datetime_value"`
	JsonValue     sql.NullString  `json:"json_value"`
}

type InstanceState struct {
	ID         int64  `json:"id"`
	SetupState string `json:"setup_state"`
	UpdatedAt  string `json:"updated_at"`
}

type Item struct {
	ID        string `json:"id"`
	LibraryID string `json:"library_id"`
	Status    string `json:"status"`
	Revision  int64  `json:"revision"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Library struct {
	ID          string `json:"id"`
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	ContentType string `json:"content_type"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}
