// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateFieldDefinition(ctx context.Context, arg CreateFieldDefinitionParams) error
	CreateItem(ctx context.Context, arg CreateItemParams) error
	CreateLibrary(ctx context.Context, arg CreateLibraryParams) error
	GetFieldValuesForItem(ctx context.Context, objectID string) ([]FieldValue, error)
	GetInstanceState(ctx context.Context) (string, error)
	GetItem(ctx context.Context, id string) (Item, error)
	GetLibrary(ctx context.Context, id string) (Library, error)
	ListFieldDefinitionsForLibrary(ctx context.Context, arg ListFieldDefinitionsForLibraryParams) ([]FieldDefinition, error)
	ListItemsForLibraryAfterCursor(ctx context.Context, arg ListItemsForLibraryAfterCursorParams) ([]Item, error)
	ListItemsForLibraryFirstPage(ctx context.Context, arg ListItemsForLibraryFirstPageParams) ([]Item, error)
	ListLibraries(ctx context.Context, arg ListLibrariesParams) ([]Library, error)
	UpsertFieldValue(ctx context.Context, arg UpsertFieldValueParams) error
	UpsertInstanceState(ctx context.Context, setupState string) error
}

var _ Querier = (*Queries)(nil)
