// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexaMediaServer.Infrastructure.Data;

#nullable disable

namespace NexaMediaServer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MediaServerContext))]
    [Migration("20251223201729_AddPromotedHubFields")]
    partial class AddPromotedHubFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("MetadataItemGenre", b =>
                {
                    b.Property<int>("MetadataItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MetadataItemId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MetadataItemGenre");
                });

            modelBuilder.Entity("MetadataItemTag", b =>
                {
                    b.Property<int>("MetadataItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MetadataItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MetadataItemTag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.CapabilityProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CapabilitiesJson");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeclaredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "Version")
                        .IsUnique();

                    b.ToTable("CapabilityProfiles");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenIp");

                    b.HasIndex("UserId", "Identifier")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Directory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibrarySectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentDirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ParentDirectoryId");

                    b.HasIndex("Path");

                    b.HasIndex("LibrarySectionId", "ParentDirectoryId", "Path")
                        .IsUnique();

                    b.ToTable("Directories");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentGenreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.JobNotificationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedItems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibrarySectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalItems")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("Status");

                    b.HasIndex("LibrarySectionId", "JobType", "Status");

                    b.ToTable("JobNotificationEntries");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.LibraryScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckpointVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckpointAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibrarySectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResumeCursor")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibrarySectionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("LibraryScans");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.LibraryScanSeenPath", b =>
                {
                    b.Property<int>("LibraryScanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryScanId", "FilePath");

                    b.HasIndex("LibraryScanId");

                    b.ToTable("LibraryScanSeenPaths");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.LibrarySection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastScannedAt");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("LibrarySections");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AudioTrackCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscType")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DocumentHasImages")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentPageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentWordCount")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileFormat")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("GameIsRom")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasChapters")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageBitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageColorSpace")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ImageDateTaken")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ImageHasExif")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetadataItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubtitleTrackCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoAspectRatio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoBitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideoBitrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodecLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodecProfile")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoColorPrimaries")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoColorRange")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoColorSpace")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoColorTransfer")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoDynamicRange")
                        .HasColumnType("TEXT");

                    b.Property<double?>("VideoFrameRate")
                        .HasColumnType("REAL");

                    b.Property<int?>("VideoHeight")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("VideoIsInterlaced")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideoWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetadataItemId");

                    b.HasIndex("SectionLocationId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MediaPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("File");

                    b.HasIndex("Hash");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("Size");

                    b.ToTable("MediaParts");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AbsoluteIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentRating")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContentRatingAge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibrarySectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUri")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetadataType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PromotedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PromotedUntil")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SortTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("NATURALSORT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbsoluteIndex");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Index");

                    b.HasIndex("LibrarySectionId");

                    b.HasIndex("MetadataType");

                    b.HasIndex("OriginalTitle");

                    b.HasIndex("ParentId");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("SortTitle");

                    b.HasIndex("Title");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("Year");

                    b.HasIndex("IsPromoted", "PromotedAt");

                    b.HasIndex("LibrarySectionId", "CreatedAt");

                    b.HasIndex("LibrarySectionId", "ReleaseDate");

                    b.HasIndex("MetadataType", "CreatedAt");

                    b.HasIndex("MetadataType", "ReleaseDate");

                    b.HasIndex("ParentId", "MetadataType");

                    b.ToTable("MetadataItems");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataItemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSkippedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastViewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetadataItemId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0f);

                    b.Property<int>("SkipCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ViewOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("LastSkippedAt");

                    b.HasIndex("LastViewedAt");

                    b.HasIndex("MetadataItemId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "MetadataItemId")
                        .IsUnique();

                    b.ToTable("MetadataItemSettings");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetadataItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelatedMetadataItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelatedMetadataItemId");

                    b.HasIndex("MetadataItemId", "RelatedMetadataItemId", "RelationType", "Text")
                        .IsUnique();

                    b.ToTable("MetadataRelations");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.PlaybackSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapabilityProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentMediaPartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMetadataItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Originator")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlaybackSessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayheadMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("playing");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityProfileId");

                    b.HasIndex("CurrentMediaPartId");

                    b.HasIndex("CurrentMetadataItemId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PlaybackSessionId")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.ToTable("PlaybackSessions");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.PlaylistGenerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cursor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaybackSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlaylistGeneratorId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Repeat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeedJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Shuffle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShuffleState")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PlaybackSessionId")
                        .IsUnique();

                    b.HasIndex("PlaylistGeneratorId")
                        .IsUnique();

                    b.ToTable("PlaylistGenerators");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.PlaylistGeneratorItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cohort")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaPartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetadataItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistGeneratorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Served")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("MediaPartId");

                    b.HasIndex("MetadataItemId");

                    b.HasIndex("PlaylistGeneratorId");

                    b.HasIndex("PlaylistGeneratorId", "SortOrder")
                        .IsUnique();

                    b.ToTable("PlaylistGeneratorItems");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.SectionLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibrarySectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastScannedAt");

                    b.HasIndex("LibrarySectionId");

                    b.HasIndex("RootPath", "LibrarySectionId")
                        .IsUnique();

                    b.ToTable("SectionsLocations");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.ServerSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedFromIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RevokedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.UserHubConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Context")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledHubTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnabledHubTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LibrarySectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Context");

                    b.HasIndex("LibrarySectionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Context", "LibrarySectionId")
                        .IsUnique();

                    b.ToTable("UserHubConfigurations");
                });

            modelBuilder.Entity("MetadataItemGenre", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", null)
                        .WithMany()
                        .HasForeignKey("MetadataItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MetadataItemTag", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", null)
                        .WithMany()
                        .HasForeignKey("MetadataItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.CapabilityProfile", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Device", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Directory", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.LibrarySection", "LibrarySection")
                        .WithMany("Directories")
                        .HasForeignKey("LibrarySectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.Directory", "ParentDirectory")
                        .WithMany("SubDirectories")
                        .HasForeignKey("ParentDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LibrarySection");

                    b.Navigation("ParentDirectory");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Genre", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.Genre", "ParentGenre")
                        .WithMany("ChildGenres")
                        .HasForeignKey("ParentGenreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGenre");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.JobNotificationEntry", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.LibrarySection", "LibrarySection")
                        .WithMany()
                        .HasForeignKey("LibrarySectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibrarySection");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.LibraryScan", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.LibrarySection", "LibrarySection")
                        .WithMany("Scans")
                        .HasForeignKey("LibrarySectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibrarySection");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.LibraryScanSeenPath", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.LibraryScan", "LibraryScan")
                        .WithMany("SeenPaths")
                        .HasForeignKey("LibraryScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryScan");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MediaItem", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", "MetadataItem")
                        .WithMany("MediaItems")
                        .HasForeignKey("MetadataItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.SectionLocation", "SectionLocation")
                        .WithMany("MediaItems")
                        .HasForeignKey("SectionLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetadataItem");

                    b.Navigation("SectionLocation");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MediaPart", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.MediaItem", "MediaItem")
                        .WithMany("Parts")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataItem", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.LibrarySection", "LibrarySection")
                        .WithMany("MetadataItems")
                        .HasForeignKey("LibrarySectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LibrarySection");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataItemSetting", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", "MetadataItem")
                        .WithMany("Settings")
                        .HasForeignKey("MetadataItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetadataItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataRelation", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", "MetadataItem")
                        .WithMany("OutgoingRelations")
                        .HasForeignKey("MetadataItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", "RelatedMetadataItem")
                        .WithMany("IncomingRelations")
                        .HasForeignKey("RelatedMetadataItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetadataItem");

                    b.Navigation("RelatedMetadataItem");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.PlaybackSession", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.CapabilityProfile", "CapabilityProfile")
                        .WithMany()
                        .HasForeignKey("CapabilityProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.MediaPart", "CurrentMediaPart")
                        .WithMany()
                        .HasForeignKey("CurrentMediaPartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", "CurrentMetadataItem")
                        .WithMany()
                        .HasForeignKey("CurrentMetadataItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapabilityProfile");

                    b.Navigation("CurrentMediaPart");

                    b.Navigation("CurrentMetadataItem");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.PlaylistGenerator", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.PlaybackSession", "PlaybackSession")
                        .WithOne("PlaylistGenerator")
                        .HasForeignKey("NexaMediaServer.Core.Entities.PlaylistGenerator", "PlaybackSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaybackSession");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.PlaylistGeneratorItem", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexaMediaServer.Core.Entities.MediaPart", "MediaPart")
                        .WithMany()
                        .HasForeignKey("MediaPartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", "MetadataItem")
                        .WithMany()
                        .HasForeignKey("MetadataItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.PlaylistGenerator", "PlaylistGenerator")
                        .WithMany("Items")
                        .HasForeignKey("PlaylistGeneratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("MediaPart");

                    b.Navigation("MetadataItem");

                    b.Navigation("PlaylistGenerator");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.SectionLocation", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.LibrarySection", "LibrarySection")
                        .WithMany("Locations")
                        .HasForeignKey("LibrarySectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibrarySection");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Session", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.Device", "Device")
                        .WithMany("Sessions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.UserHubConfiguration", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.LibrarySection", "LibrarySection")
                        .WithMany()
                        .HasForeignKey("LibrarySectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NexaMediaServer.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibrarySection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Device", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Directory", b =>
                {
                    b.Navigation("SubDirectories");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Genre", b =>
                {
                    b.Navigation("ChildGenres");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.LibraryScan", b =>
                {
                    b.Navigation("SeenPaths");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.LibrarySection", b =>
                {
                    b.Navigation("Directories");

                    b.Navigation("Locations");

                    b.Navigation("MetadataItems");

                    b.Navigation("Scans");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MediaItem", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("IncomingRelations");

                    b.Navigation("MediaItems");

                    b.Navigation("OutgoingRelations");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.PlaybackSession", b =>
                {
                    b.Navigation("PlaylistGenerator");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.PlaylistGenerator", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.SectionLocation", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
