// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NexaMediaServer.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddScanCheckpointing : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_LibraryScan_LibrarySections_LibrarySectionId",
                table: "LibraryScan");

            migrationBuilder.DropPrimaryKey(
                name: "PK_LibraryScan",
                table: "LibraryScan");

            migrationBuilder.RenameTable(
                name: "LibraryScan",
                newName: "LibraryScans");

            migrationBuilder.RenameIndex(
                name: "IX_LibraryScan_Status",
                table: "LibraryScans",
                newName: "IX_LibraryScans_Status");

            migrationBuilder.RenameIndex(
                name: "IX_LibraryScan_StartedAt",
                table: "LibraryScans",
                newName: "IX_LibraryScans_StartedAt");

            migrationBuilder.RenameIndex(
                name: "IX_LibraryScan_LibrarySectionId",
                table: "LibraryScans",
                newName: "IX_LibraryScans_LibrarySectionId");

            migrationBuilder.AddColumn<int>(
                name: "CheckpointVersion",
                table: "LibraryScans",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "CurrentStage",
                table: "LibraryScans",
                type: "TEXT",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "LastCheckpointAt",
                table: "LibraryScans",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ResumeCursor",
                table: "LibraryScans",
                type: "TEXT",
                maxLength: 4096,
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_LibraryScans",
                table: "LibraryScans",
                column: "Id");

            migrationBuilder.CreateTable(
                name: "LibraryScanSeenPaths",
                columns: table => new
                {
                    LibraryScanId = table.Column<int>(type: "INTEGER", nullable: false),
                    FilePath = table.Column<string>(type: "TEXT", maxLength: 4096, nullable: false),
                    SeenAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LibraryScanSeenPaths", x => new { x.LibraryScanId, x.FilePath });
                    table.ForeignKey(
                        name: "FK_LibraryScanSeenPaths_LibraryScans_LibraryScanId",
                        column: x => x.LibraryScanId,
                        principalTable: "LibraryScans",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_LibraryScanSeenPaths_LibraryScanId",
                table: "LibraryScanSeenPaths",
                column: "LibraryScanId");

            migrationBuilder.AddForeignKey(
                name: "FK_LibraryScans_LibrarySections_LibrarySectionId",
                table: "LibraryScans",
                column: "LibrarySectionId",
                principalTable: "LibrarySections",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_LibraryScans_LibrarySections_LibrarySectionId",
                table: "LibraryScans");

            migrationBuilder.DropTable(
                name: "LibraryScanSeenPaths");

            migrationBuilder.DropPrimaryKey(
                name: "PK_LibraryScans",
                table: "LibraryScans");

            migrationBuilder.DropColumn(
                name: "CheckpointVersion",
                table: "LibraryScans");

            migrationBuilder.DropColumn(
                name: "CurrentStage",
                table: "LibraryScans");

            migrationBuilder.DropColumn(
                name: "LastCheckpointAt",
                table: "LibraryScans");

            migrationBuilder.DropColumn(
                name: "ResumeCursor",
                table: "LibraryScans");

            migrationBuilder.RenameTable(
                name: "LibraryScans",
                newName: "LibraryScan");

            migrationBuilder.RenameIndex(
                name: "IX_LibraryScans_Status",
                table: "LibraryScan",
                newName: "IX_LibraryScan_Status");

            migrationBuilder.RenameIndex(
                name: "IX_LibraryScans_StartedAt",
                table: "LibraryScan",
                newName: "IX_LibraryScan_StartedAt");

            migrationBuilder.RenameIndex(
                name: "IX_LibraryScans_LibrarySectionId",
                table: "LibraryScan",
                newName: "IX_LibraryScan_LibrarySectionId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_LibraryScan",
                table: "LibraryScan",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_LibraryScan_LibrarySections_LibrarySectionId",
                table: "LibraryScan",
                column: "LibrarySectionId",
                principalTable: "LibrarySections",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
