// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NexaMediaServer.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddPromotedHubFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsPromoted",
                table: "MetadataItems",
                type: "INTEGER",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "PromotedAt",
                table: "MetadataItems",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "PromotedUntil",
                table: "MetadataItems",
                type: "TEXT",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItems_IsPromoted_PromotedAt",
                table: "MetadataItems",
                columns: new[] { "IsPromoted", "PromotedAt" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_MetadataItems_IsPromoted_PromotedAt",
                table: "MetadataItems");

            migrationBuilder.DropColumn(
                name: "IsPromoted",
                table: "MetadataItems");

            migrationBuilder.DropColumn(
                name: "PromotedAt",
                table: "MetadataItems");

            migrationBuilder.DropColumn(
                name: "PromotedUntil",
                table: "MetadataItems");
        }
    }
}
