// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NexaMediaServer.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AspNetRoles",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    NormalizedName = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoles", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUsers",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    LastActiveAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UserName = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    NormalizedUserName = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    Email = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    NormalizedEmail = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    EmailConfirmed = table.Column<bool>(type: "INTEGER", nullable: false),
                    PasswordHash = table.Column<string>(type: "TEXT", nullable: true),
                    SecurityStamp = table.Column<string>(type: "TEXT", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "TEXT", nullable: true),
                    PhoneNumber = table.Column<string>(type: "TEXT", nullable: true),
                    PhoneNumberConfirmed = table.Column<bool>(type: "INTEGER", nullable: false),
                    TwoFactorEnabled = table.Column<bool>(type: "INTEGER", nullable: false),
                    LockoutEnd = table.Column<DateTimeOffset>(type: "TEXT", nullable: true),
                    LockoutEnabled = table.Column<bool>(type: "INTEGER", nullable: false),
                    AccessFailedCount = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUsers", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "LibrarySections",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Uuid = table.Column<Guid>(type: "TEXT", nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 128, nullable: false),
                    SortName = table.Column<string>(type: "TEXT", maxLength: 128, nullable: false),
                    Type = table.Column<int>(type: "INTEGER", nullable: false),
                    LastScannedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    Settings = table.Column<string>(type: "TEXT", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LibrarySections", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ServerSettings",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Key = table.Column<string>(type: "TEXT", nullable: false),
                    Value = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ServerSettings", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AspNetRoleClaims",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    RoleId = table.Column<string>(type: "TEXT", nullable: false),
                    ClaimType = table.Column<string>(type: "TEXT", nullable: true),
                    ClaimValue = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoleClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetRoleClaims_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserClaims",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    UserId = table.Column<string>(type: "TEXT", nullable: false),
                    ClaimType = table.Column<string>(type: "TEXT", nullable: true),
                    ClaimValue = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetUserClaims_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserLogins",
                columns: table => new
                {
                    LoginProvider = table.Column<string>(type: "TEXT", nullable: false),
                    ProviderKey = table.Column<string>(type: "TEXT", nullable: false),
                    ProviderDisplayName = table.Column<string>(type: "TEXT", nullable: true),
                    UserId = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserLogins", x => new { x.LoginProvider, x.ProviderKey });
                    table.ForeignKey(
                        name: "FK_AspNetUserLogins_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserRoles",
                columns: table => new
                {
                    UserId = table.Column<string>(type: "TEXT", nullable: false),
                    RoleId = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserRoles", x => new { x.UserId, x.RoleId });
                    table.ForeignKey(
                        name: "FK_AspNetUserRoles_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AspNetUserRoles_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserTokens",
                columns: table => new
                {
                    UserId = table.Column<string>(type: "TEXT", nullable: false),
                    LoginProvider = table.Column<string>(type: "TEXT", nullable: false),
                    Name = table.Column<string>(type: "TEXT", nullable: false),
                    Value = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserTokens", x => new { x.UserId, x.LoginProvider, x.Name });
                    table.ForeignKey(
                        name: "FK_AspNetUserTokens_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Directories",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    LibrarySectionId = table.Column<int>(type: "INTEGER", nullable: false),
                    ParentDirectoryId = table.Column<int>(type: "INTEGER", nullable: true),
                    Path = table.Column<string>(type: "TEXT", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Directories", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Directories_Directories_ParentDirectoryId",
                        column: x => x.ParentDirectoryId,
                        principalTable: "Directories",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Directories_LibrarySections_LibrarySectionId",
                        column: x => x.LibrarySectionId,
                        principalTable: "LibrarySections",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "LibraryScan",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    LibrarySectionId = table.Column<int>(type: "INTEGER", nullable: false),
                    Status = table.Column<int>(type: "INTEGER", nullable: false),
                    StartedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    CompletedAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                    TotalFiles = table.Column<int>(type: "INTEGER", nullable: false),
                    ProcessedFiles = table.Column<int>(type: "INTEGER", nullable: false),
                    ItemsAdded = table.Column<int>(type: "INTEGER", nullable: false),
                    ItemsUpdated = table.Column<int>(type: "INTEGER", nullable: false),
                    ItemsRemoved = table.Column<int>(type: "INTEGER", nullable: false),
                    ErrorMessage = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LibraryScan", x => x.Id);
                    table.ForeignKey(
                        name: "FK_LibraryScan_LibrarySections_LibrarySectionId",
                        column: x => x.LibrarySectionId,
                        principalTable: "LibrarySections",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "MetadataItems",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Uuid = table.Column<Guid>(type: "TEXT", nullable: false),
                    MetadataType = table.Column<int>(type: "INTEGER", nullable: false),
                    Title = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false),
                    SortTitle = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false, collation: "NATURALSORT"),
                    OriginalTitle = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    Summary = table.Column<string>(type: "TEXT", nullable: true),
                    Tagline = table.Column<string>(type: "TEXT", maxLength: 256, nullable: true),
                    ContentRating = table.Column<string>(type: "TEXT", nullable: true),
                    ContentRatingAge = table.Column<int>(type: "INTEGER", nullable: true),
                    ReleaseDate = table.Column<DateOnly>(type: "TEXT", nullable: true),
                    Year = table.Column<int>(type: "INTEGER", nullable: true),
                    Index = table.Column<int>(type: "INTEGER", nullable: true),
                    AbsoluteIndex = table.Column<int>(type: "INTEGER", nullable: true),
                    Duration = table.Column<int>(type: "INTEGER", nullable: true),
                    ThumbUri = table.Column<string>(type: "TEXT", nullable: true),
                    ArtUri = table.Column<string>(type: "TEXT", nullable: true),
                    LogoUri = table.Column<string>(type: "TEXT", nullable: true),
                    LibrarySectionId = table.Column<int>(type: "INTEGER", nullable: false),
                    ParentId = table.Column<int>(type: "INTEGER", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MetadataItems", x => x.Id);
                    table.ForeignKey(
                        name: "FK_MetadataItems_LibrarySections_LibrarySectionId",
                        column: x => x.LibrarySectionId,
                        principalTable: "LibrarySections",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_MetadataItems_MetadataItems_ParentId",
                        column: x => x.ParentId,
                        principalTable: "MetadataItems",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "SectionsLocations",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    LibrarySectionId = table.Column<int>(type: "INTEGER", nullable: false),
                    RootPath = table.Column<string>(type: "TEXT", nullable: false),
                    Available = table.Column<bool>(type: "INTEGER", nullable: false),
                    LastScannedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SectionsLocations", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SectionsLocations_LibrarySections_LibrarySectionId",
                        column: x => x.LibrarySectionId,
                        principalTable: "LibrarySections",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "MetadataItemSettings",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    UserId = table.Column<string>(type: "TEXT", maxLength: 450, nullable: false),
                    MetadataItemId = table.Column<int>(type: "INTEGER", nullable: false),
                    Rating = table.Column<float>(type: "REAL", nullable: false, defaultValue: 0f),
                    ViewOffset = table.Column<int>(type: "INTEGER", nullable: false, defaultValue: 0),
                    ViewCount = table.Column<int>(type: "INTEGER", nullable: false, defaultValue: 0),
                    LastViewedAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                    SkipCount = table.Column<int>(type: "INTEGER", nullable: false, defaultValue: 0),
                    LastSkippedAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MetadataItemSettings", x => x.Id);
                    table.ForeignKey(
                        name: "FK_MetadataItemSettings_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_MetadataItemSettings_MetadataItems_MetadataItemId",
                        column: x => x.MetadataItemId,
                        principalTable: "MetadataItems",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "MetadataRelations",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    MetadataItemId = table.Column<int>(type: "INTEGER", nullable: false),
                    RelatedMetadataItemId = table.Column<int>(type: "INTEGER", nullable: false),
                    RelationType = table.Column<int>(type: "INTEGER", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MetadataRelations", x => x.Id);
                    table.ForeignKey(
                        name: "FK_MetadataRelations_MetadataItems_MetadataItemId",
                        column: x => x.MetadataItemId,
                        principalTable: "MetadataItems",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_MetadataRelations_MetadataItems_RelatedMetadataItemId",
                        column: x => x.RelatedMetadataItemId,
                        principalTable: "MetadataItems",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "MediaItems",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    MetadataItemId = table.Column<int>(type: "INTEGER", nullable: false),
                    SectionLocationId = table.Column<int>(type: "INTEGER", nullable: false),
                    FileSizeBytes = table.Column<long>(type: "INTEGER", nullable: true),
                    FileFormat = table.Column<string>(type: "TEXT", nullable: true),
                    Duration = table.Column<TimeSpan>(type: "TEXT", nullable: true),
                    HasChapters = table.Column<bool>(type: "INTEGER", nullable: true),
                    ChapterCount = table.Column<int>(type: "INTEGER", nullable: true),
                    IsDisc = table.Column<bool>(type: "INTEGER", nullable: false),
                    DiscType = table.Column<int>(type: "INTEGER", nullable: true),
                    DiscTitle = table.Column<string>(type: "TEXT", nullable: true),
                    DiscId = table.Column<string>(type: "TEXT", nullable: true),
                    VideoCodec = table.Column<string>(type: "TEXT", nullable: true),
                    VideoCodecProfile = table.Column<string>(type: "TEXT", nullable: true),
                    VideoCodecLevel = table.Column<string>(type: "TEXT", nullable: true),
                    VideoBitrate = table.Column<int>(type: "INTEGER", nullable: true),
                    VideoWidth = table.Column<int>(type: "INTEGER", nullable: true),
                    VideoHeight = table.Column<int>(type: "INTEGER", nullable: true),
                    VideoAspectRatio = table.Column<string>(type: "TEXT", nullable: true),
                    VideoFrameRate = table.Column<double>(type: "REAL", nullable: true),
                    VideoIsInterlaced = table.Column<bool>(type: "INTEGER", nullable: true),
                    VideoBitDepth = table.Column<int>(type: "INTEGER", nullable: true),
                    VideoColorSpace = table.Column<string>(type: "TEXT", nullable: true),
                    VideoColorPrimaries = table.Column<string>(type: "TEXT", nullable: true),
                    VideoColorTransfer = table.Column<string>(type: "TEXT", nullable: true),
                    VideoColorRange = table.Column<string>(type: "TEXT", nullable: true),
                    VideoDynamicRange = table.Column<string>(type: "TEXT", nullable: true),
                    AudioTrackCount = table.Column<int>(type: "INTEGER", nullable: true),
                    SubtitleTrackCount = table.Column<int>(type: "INTEGER", nullable: true),
                    ImageWidth = table.Column<int>(type: "INTEGER", nullable: true),
                    ImageHeight = table.Column<int>(type: "INTEGER", nullable: true),
                    ImageBitDepth = table.Column<int>(type: "INTEGER", nullable: true),
                    ImageColorSpace = table.Column<string>(type: "TEXT", nullable: true),
                    ImageHasExif = table.Column<bool>(type: "INTEGER", nullable: true),
                    ImageDateTaken = table.Column<DateTimeOffset>(type: "TEXT", nullable: true),
                    DocumentPageCount = table.Column<int>(type: "INTEGER", nullable: true),
                    DocumentWordCount = table.Column<int>(type: "INTEGER", nullable: true),
                    DocumentHasImages = table.Column<bool>(type: "INTEGER", nullable: true),
                    GameIsRom = table.Column<bool>(type: "INTEGER", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MediaItems", x => x.Id);
                    table.ForeignKey(
                        name: "FK_MediaItems_MetadataItems_MetadataItemId",
                        column: x => x.MetadataItemId,
                        principalTable: "MetadataItems",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_MediaItems_SectionsLocations_SectionLocationId",
                        column: x => x.SectionLocationId,
                        principalTable: "SectionsLocations",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "MediaParts",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    MediaItemId = table.Column<int>(type: "INTEGER", nullable: false),
                    Hash = table.Column<string>(type: "TEXT", maxLength: 40, nullable: true),
                    File = table.Column<string>(type: "TEXT", nullable: false),
                    Size = table.Column<long>(type: "INTEGER", nullable: true),
                    Duration = table.Column<double>(type: "REAL", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    DeletedAt = table.Column<DateTime>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MediaParts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_MediaParts_MediaItems_MediaItemId",
                        column: x => x.MediaItemId,
                        principalTable: "MediaItems",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AspNetRoleClaims_RoleId",
                table: "AspNetRoleClaims",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "RoleNameIndex",
                table: "AspNetRoles",
                column: "NormalizedName",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserClaims_UserId",
                table: "AspNetUserClaims",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserLogins_UserId",
                table: "AspNetUserLogins",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserRoles_RoleId",
                table: "AspNetUserRoles",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "EmailIndex",
                table: "AspNetUsers",
                column: "NormalizedEmail");

            migrationBuilder.CreateIndex(
                name: "UserNameIndex",
                table: "AspNetUsers",
                column: "NormalizedUserName",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Directories_DeletedAt",
                table: "Directories",
                column: "DeletedAt");

            migrationBuilder.CreateIndex(
                name: "IX_Directories_LibrarySectionId_ParentDirectoryId_Path",
                table: "Directories",
                columns: new[] { "LibrarySectionId", "ParentDirectoryId", "Path" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Directories_ParentDirectoryId",
                table: "Directories",
                column: "ParentDirectoryId");

            migrationBuilder.CreateIndex(
                name: "IX_Directories_Path",
                table: "Directories",
                column: "Path");

            migrationBuilder.CreateIndex(
                name: "IX_LibraryScan_LibrarySectionId",
                table: "LibraryScan",
                column: "LibrarySectionId");

            migrationBuilder.CreateIndex(
                name: "IX_LibraryScan_StartedAt",
                table: "LibraryScan",
                column: "StartedAt");

            migrationBuilder.CreateIndex(
                name: "IX_LibraryScan_Status",
                table: "LibraryScan",
                column: "Status");

            migrationBuilder.CreateIndex(
                name: "IX_LibrarySections_LastScannedAt",
                table: "LibrarySections",
                column: "LastScannedAt");

            migrationBuilder.CreateIndex(
                name: "IX_LibrarySections_Name",
                table: "LibrarySections",
                column: "Name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_LibrarySections_Type",
                table: "LibrarySections",
                column: "Type");

            migrationBuilder.CreateIndex(
                name: "IX_MediaItems_MetadataItemId",
                table: "MediaItems",
                column: "MetadataItemId");

            migrationBuilder.CreateIndex(
                name: "IX_MediaItems_SectionLocationId",
                table: "MediaItems",
                column: "SectionLocationId");

            migrationBuilder.CreateIndex(
                name: "IX_MediaParts_DeletedAt",
                table: "MediaParts",
                column: "DeletedAt");

            migrationBuilder.CreateIndex(
                name: "IX_MediaParts_File",
                table: "MediaParts",
                column: "File");

            migrationBuilder.CreateIndex(
                name: "IX_MediaParts_Hash",
                table: "MediaParts",
                column: "Hash");

            migrationBuilder.CreateIndex(
                name: "IX_MediaParts_MediaItemId",
                table: "MediaParts",
                column: "MediaItemId");

            migrationBuilder.CreateIndex(
                name: "IX_MediaParts_Size",
                table: "MediaParts",
                column: "Size");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItems_AbsoluteIndex",
                table: "MetadataItems",
                column: "AbsoluteIndex");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItems_Index",
                table: "MetadataItems",
                column: "Index");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItems_LibrarySectionId",
                table: "MetadataItems",
                column: "LibrarySectionId");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItems_MetadataType",
                table: "MetadataItems",
                column: "MetadataType");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItems_OriginalTitle",
                table: "MetadataItems",
                column: "OriginalTitle");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItems_ParentId",
                table: "MetadataItems",
                column: "ParentId");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItems_SortTitle",
                table: "MetadataItems",
                column: "SortTitle");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItems_Title",
                table: "MetadataItems",
                column: "Title");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItems_Uuid",
                table: "MetadataItems",
                column: "Uuid",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItemSettings_LastSkippedAt",
                table: "MetadataItemSettings",
                column: "LastSkippedAt");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItemSettings_LastViewedAt",
                table: "MetadataItemSettings",
                column: "LastViewedAt");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItemSettings_MetadataItemId",
                table: "MetadataItemSettings",
                column: "MetadataItemId");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItemSettings_UserId",
                table: "MetadataItemSettings",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItemSettings_UserId_MetadataItemId",
                table: "MetadataItemSettings",
                columns: new[] { "UserId", "MetadataItemId" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_MetadataRelations_MetadataItemId_RelatedMetadataItemId_RelationType",
                table: "MetadataRelations",
                columns: new[] { "MetadataItemId", "RelatedMetadataItemId", "RelationType" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_MetadataRelations_RelatedMetadataItemId",
                table: "MetadataRelations",
                column: "RelatedMetadataItemId");

            migrationBuilder.CreateIndex(
                name: "IX_SectionsLocations_LastScannedAt",
                table: "SectionsLocations",
                column: "LastScannedAt");

            migrationBuilder.CreateIndex(
                name: "IX_SectionsLocations_LibrarySectionId",
                table: "SectionsLocations",
                column: "LibrarySectionId");

            migrationBuilder.CreateIndex(
                name: "IX_SectionsLocations_RootPath_LibrarySectionId",
                table: "SectionsLocations",
                columns: new[] { "RootPath", "LibrarySectionId" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AspNetRoleClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserLogins");

            migrationBuilder.DropTable(
                name: "AspNetUserRoles");

            migrationBuilder.DropTable(
                name: "AspNetUserTokens");

            migrationBuilder.DropTable(
                name: "Directories");

            migrationBuilder.DropTable(
                name: "LibraryScan");

            migrationBuilder.DropTable(
                name: "MediaParts");

            migrationBuilder.DropTable(
                name: "MetadataItemSettings");

            migrationBuilder.DropTable(
                name: "MetadataRelations");

            migrationBuilder.DropTable(
                name: "ServerSettings");

            migrationBuilder.DropTable(
                name: "AspNetRoles");

            migrationBuilder.DropTable(
                name: "MediaItems");

            migrationBuilder.DropTable(
                name: "AspNetUsers");

            migrationBuilder.DropTable(
                name: "MetadataItems");

            migrationBuilder.DropTable(
                name: "SectionsLocations");

            migrationBuilder.DropTable(
                name: "LibrarySections");
        }
    }
}
