// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NexaMediaServer.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddOriginalSortOrderToPlaylistGeneratorItem : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "OriginalSortOrder",
                table: "PlaylistGeneratorItems",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);

            // Backfill existing rows: set OriginalSortOrder = SortOrder
            migrationBuilder.Sql("UPDATE PlaylistGeneratorItems SET OriginalSortOrder = SortOrder;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "OriginalSortOrder",
                table: "PlaylistGeneratorItems");
        }
    }
}
