// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NexaMediaServer.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddViewOptions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_MetadataItemSettings_UserId_LastViewedAt",
                table: "MetadataItemSettings",
                columns: new[] { "UserId", "LastViewedAt" });

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItemSettings_UserId_ViewCount",
                table: "MetadataItemSettings",
                columns: new[] { "UserId", "ViewCount" });

            migrationBuilder.CreateIndex(
                name: "IX_MetadataItemSettings_UserId_ViewOffset",
                table: "MetadataItemSettings",
                columns: new[] { "UserId", "ViewOffset" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_MetadataItemSettings_UserId_LastViewedAt",
                table: "MetadataItemSettings");

            migrationBuilder.DropIndex(
                name: "IX_MetadataItemSettings_UserId_ViewCount",
                table: "MetadataItemSettings");

            migrationBuilder.DropIndex(
                name: "IX_MetadataItemSettings_UserId_ViewOffset",
                table: "MetadataItemSettings");
        }
    }
}
