// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NexaMediaServer.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddFieldGroupSupport : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "FieldGroupAssignmentsJson",
                table: "UserDetailFieldConfigurations",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "FieldGroupsJson",
                table: "UserDetailFieldConfigurations",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "FieldGroupAssignmentsJson",
                table: "DetailFieldConfigurationOverrides",
                type: "TEXT",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "FieldGroupsJson",
                table: "DetailFieldConfigurationOverrides",
                type: "TEXT",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "FieldGroupAssignmentsJson",
                table: "UserDetailFieldConfigurations");

            migrationBuilder.DropColumn(
                name: "FieldGroupsJson",
                table: "UserDetailFieldConfigurations");

            migrationBuilder.DropColumn(
                name: "FieldGroupAssignmentsJson",
                table: "DetailFieldConfigurationOverrides");

            migrationBuilder.DropColumn(
                name: "FieldGroupsJson",
                table: "DetailFieldConfigurationOverrides");
        }
    }
}
