// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexaMediaServer.Infrastructure.Data;

#nullable disable

namespace NexaMediaServer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MediaServerContext))]
    partial class MediaServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Directory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibrarySectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentDirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ParentDirectoryId");

                    b.HasIndex("Path");

                    b.HasIndex("LibrarySectionId", "ParentDirectoryId", "Path")
                        .IsUnique();

                    b.ToTable("Directories");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.LibraryScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibrarySectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibrarySectionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("LibraryScan");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.LibrarySection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastScannedAt");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("LibrarySections");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AudioTrackCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscType")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DocumentHasImages")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentPageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentWordCount")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileFormat")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("GameIsRom")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasChapters")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageBitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageColorSpace")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ImageDateTaken")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ImageHasExif")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetadataItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubtitleTrackCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoAspectRatio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoBitDepth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideoBitrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodecLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodecProfile")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoColorPrimaries")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoColorRange")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoColorSpace")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoColorTransfer")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoDynamicRange")
                        .HasColumnType("TEXT");

                    b.Property<double?>("VideoFrameRate")
                        .HasColumnType("REAL");

                    b.Property<int?>("VideoHeight")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("VideoIsInterlaced")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideoWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MetadataItemId");

                    b.HasIndex("SectionLocationId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MediaPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("File");

                    b.HasIndex("Hash");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("Size");

                    b.ToTable("MediaParts");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AbsoluteIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentRating")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContentRatingAge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibrarySectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUri")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetadataType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SortTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("NATURALSORT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbsoluteIndex");

                    b.HasIndex("Index");

                    b.HasIndex("LibrarySectionId");

                    b.HasIndex("MetadataType");

                    b.HasIndex("OriginalTitle");

                    b.HasIndex("ParentId");

                    b.HasIndex("SortTitle");

                    b.HasIndex("Title");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("MetadataItems");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataItemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSkippedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastViewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetadataItemId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0f);

                    b.Property<int>("SkipCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("ViewOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("LastSkippedAt");

                    b.HasIndex("LastViewedAt");

                    b.HasIndex("MetadataItemId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "MetadataItemId")
                        .IsUnique();

                    b.ToTable("MetadataItemSettings");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.SectionLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibrarySectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastScannedAt");

                    b.HasIndex("LibrarySectionId");

                    b.HasIndex("RootPath", "LibrarySectionId")
                        .IsUnique();

                    b.ToTable("SectionsLocations");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.ServerSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServerSettings");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Directory", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.LibrarySection", "LibrarySection")
                        .WithMany("Directories")
                        .HasForeignKey("LibrarySectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.Directory", "ParentDirectory")
                        .WithMany("SubDirectories")
                        .HasForeignKey("ParentDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LibrarySection");

                    b.Navigation("ParentDirectory");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.LibraryScan", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.LibrarySection", "LibrarySection")
                        .WithMany("Scans")
                        .HasForeignKey("LibrarySectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibrarySection");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MediaItem", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", "MetadataItem")
                        .WithMany("MediaItems")
                        .HasForeignKey("MetadataItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.SectionLocation", "SectionLocation")
                        .WithMany("MediaItems")
                        .HasForeignKey("SectionLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetadataItem");

                    b.Navigation("SectionLocation");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MediaPart", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.MediaItem", "MediaItem")
                        .WithMany("Parts")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataItem", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.LibrarySection", "LibrarySection")
                        .WithMany("MetadataItems")
                        .HasForeignKey("LibrarySectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LibrarySection");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataItemSetting", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.MetadataItem", "MetadataItem")
                        .WithMany("Settings")
                        .HasForeignKey("MetadataItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexaMediaServer.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetadataItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.SectionLocation", b =>
                {
                    b.HasOne("NexaMediaServer.Core.Entities.LibrarySection", "LibrarySection")
                        .WithMany("Locations")
                        .HasForeignKey("LibrarySectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibrarySection");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.Directory", b =>
                {
                    b.Navigation("SubDirectories");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.LibrarySection", b =>
                {
                    b.Navigation("Directories");

                    b.Navigation("Locations");

                    b.Navigation("MetadataItems");

                    b.Navigation("Scans");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MediaItem", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.MetadataItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MediaItems");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("NexaMediaServer.Core.Entities.SectionLocation", b =>
                {
                    b.Navigation("MediaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
